# ---------------------------------------------------
# My GisHubActions Basic file
#
# Avrinsky Nikita
#----------------------------------------------------

name: My-GitHubAction-Basics
env:
 APPLICATION_NAME: "MyFlask"
 DEPLOY_PAKADGE_NAME    : "foo_bar_deploy_ver-${{ github.sha }}"
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print hello message
      run: echo "Hello world from testing job"
      
    - name: Execute few commands
      run: |
       echo "Hello message 1"
       echo "Hello message 2"
       echo "Application name: ${{ env.APPLICATION_NAME }}"
       
    - name: List current folder
      run: ls -la
      
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    
    steps:
    - name: Print hello message
      run: echo "Hello world from testing job" 
    
    - name: Deploymet package
      run: echo "Deployment package name is ${{env.DEPLOY_PACKAGE_NAME}}"
