# ---------------------------------------------------
# My GisHubActions Basic file
#
# Avrinsky Nikita
#----------------------------------------------------

name: My-GitHubAction-Basics
env:
 APPLICATION_NAME: "MyFlask"
 DEPLOY_PACKAGE_NAME    : "foo_bar_deploy_ver-${{ github.sha }}"
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print hello message
      run: echo "Hello world from testing job"
      
    - name: Clone repository
      uses: actions/checkout@v1
       
    - name: List current folder
      run: ls -la
      
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    env:
     VAR1 : "This is Variable 1"
    
    steps:
    - name: Print hello message
      run: echo "Hello world from testing job" 
    
    - name: Print a few variables
      run: |
       echo "Job Variable = ${{ VAR1 }}"
       echo "Local variable = $LOCAL_VAR"
      env:
       LOCAL_VAR: "This is local job variable"
    
    - name: Deploymet package
      run: echo "Deployment package name is ${{env.DEPLOY_PACKAGE_NAME}}"
    
    - name: Test some packages if they are here 1
      run: aws --version
    
    - name: Test some packages if they are here 2
      run: zip
